"""Nội dung điều khoản dùng chung cho UI và tài liệu; không thay giấy phép MIT."""
TERMS_VERSION = '2026-10-07.1'
TERMS_SECTIONS = [
    ('1. Phạm vi ứng dụng', 'Trích xuất hóa đơn do Lê Minh Triết (MinhTrietEras) phát triển để đọc hóa đơn XML/PDF và tổng hợp sang Excel. Ứng dụng hỗ trợ công việc nhập liệu; không thay thế hóa đơn gốc, phần mềm kế toán, tư vấn thuế hoặc xác minh tính hợp pháp/chữ ký số của hóa đơn.'),
    ('2. Sử dụng và quyền đối với phần mềm', 'Bạn chỉ nên xử lý các tài liệu mà mình có quyền sử dụng và chịu trách nhiệm về mục đích sử dụng hợp pháp. Mã nguồn được cấp phép MIT theo file LICENSE đi kèm, gồm quyền sử dụng, sửa đổi và phân phối với thông báo bản quyền/giấy phép được giữ theo MIT. Điều khoản này không thu hẹp các quyền đã cấp trong LICENSE. Các thành phần bên thứ ba tuân theo giấy phép riêng đi kèm.'),
    ('3. Dữ liệu và kết nối mạng', 'Bản ứng dụng hiện tại xử lý hóa đơn trên máy của bạn, lưu Excel vào vị trí bạn chọn và không gửi nội dung hóa đơn lên máy chủ tác giả. Cấu hình, phiên bản điều khoản đã chấp nhận và thời điểm chấp nhận được lưu tại máy. Sau thiết lập, chức năng kiểm tra cập nhật có thể kết nối GitHub; việc mở website/liên kết tải xuống cũng tạo kết nối mạng. Những dịch vụ này nhận thông tin kết nối thông thường như địa chỉ IP theo chính sách của họ. Góp ý là tùy chọn: chỉ khi bạn tích cho phép và bấm Gửi, ứng dụng mới gửi nội dung góp ý, email nếu bạn cung cấp, phiên bản app và mã xác nhận đồng ý tới leminhtriet.com để tác giả tiếp nhận trong trang quản trị. Không tự đính kèm hóa đơn, Excel hoặc đường dẫn máy; hãy tránh nhập dữ liệu nhạy cảm trong góp ý. Website nhận thông tin kết nối thông thường, dùng mã băm địa chỉ kết nối thay đổi theo giờ để giới hạn gửi và có thể có log hạ tầng theo chính sách website. Không tự gửi lại khi lỗi; bạn quyết định thử lại. Bản nháp chưa gửi chỉ giữ trong bộ nhớ phiên app. Bạn có thể liên hệ tác giả để yêu cầu xử lý/xóa góp ý đã gửi. Nếu chọn thư mục đồng bộ như OneDrive, dữ liệu có thể được dịch vụ đó đồng bộ theo cấu hình của bạn.'),
    ('4. Kiểm tra kết quả và sao lưu', 'Cấu trúc hóa đơn khác nhau có thể khiến việc trích xuất thiếu hoặc sai dữ liệu. Trước khi dùng kết quả để hạch toán, kê khai hoặc thanh toán, hãy đối chiếu số hóa đơn, ký hiệu, bên bán/mua, mặt hàng, tiền và thuế với tài liệu gốc. Hãy giữ hóa đơn gốc và sao lưu Excel trước thao tác ghi đè, xóa dữ liệu hoặc nâng cấp. Chỉ mở xem hóa đơn trong ứng dụng không ghi thay đổi vào Excel.'),
    ('5. Bảo đảm và trách nhiệm', 'Phần mềm được cung cấp theo tình trạng hiện có, với phạm vi bảo đảm và trách nhiệm theo LICENSE và pháp luật áp dụng. Không cam kết mọi mẫu hóa đơn đều được đọc chính xác, không có lỗi hoặc luôn tương thích với mọi thiết bị. Các nội dung này không loại trừ những quyền của người dùng hoặc nghĩa vụ của tác giả mà pháp luật không cho phép loại trừ.'),
    ('6. Cập nhật và hỗ trợ', 'Bạn có thể thay đổi nơi lưu và màu giao diện trong Cài đặt. Nên tải bản cập nhật từ kho dự án chính thức github.com/leminhtrietit/trichxuathoadon hoặc website leminhtriet.com. Khi báo lỗi, hãy che thông tin khách hàng, mã số thuế, số tài khoản và nội dung nhạy cảm không cần thiết. Việc hỗ trợ không có cam kết thời gian xử lý cố định.'),
    ('7. Chấp nhận và thay đổi điều khoản', 'Hãy đọc điều khoản trước khi bấm Chấp nhận và bắt đầu. Nếu chưa đồng ý, bạn có thể đóng ứng dụng; thiết lập sẽ chưa được đánh dấu hoàn tất. Khi nội dung điều khoản thay đổi, ứng dụng sẽ hiển thị phiên bản mới để bạn xem và chấp nhận trước khi tiếp tục. Xác nhận này chỉ lưu tại máy, không được gửi cho tác giả.')
]
