// Đọc UI với fixture cô lập; xác minh workbook giữ nguyên byte khi xem.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { chromium } = require('playwright');
(async () => {
    const root = path.resolve(__dirname, '..');
    const info = JSON.parse(fs.readFileSync(path.join(root, 'build/scan-regression-info.json'), 'utf8'));
    const browser = await chromium.launch({channel:'msedge',headless:true});
    try {
        const page = await browser.newPage({viewport:{width:1320,height:860}});
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        const status = await (await page.request.get(info.url+'/api/status')).json();
        assert.ok(path.resolve(status.excel_path).startsWith(path.dirname(path.resolve(info.folder))+path.sep));
        assert.ok(path.resolve(info.folder).startsWith(path.join(root,'build')+path.sep));
        const hash = () => crypto.createHash('sha256').update(fs.readFileSync(status.excel_path)).digest('hex');
        const before = hash();
        const writes = [];
        page.on('request', request => { if (request.method() !== 'GET' && /save-to-excel|clear|init-excel/.test(request.url())) writes.push(request.url()); });
        await page.route('**/api/check-update', route => route.fulfill({json:{success:true,current_version:info.version,latest_version:info.version,has_update:false}}));
        await page.goto(info.url);
        await page.locator('#startup-screen').waitFor({state:'detached'});
        assert.deepEqual(await page.locator('nav .nav-tab span').allTextContents(), ['Trích xuất hóa đơn','0','Tổng quan','1','Danh sách hóa đơn','Chi tiết hóa đơn','0']);
        await page.locator('[data-tab="tab-excel"]').click();
        await page.locator('#excel-table-body tr[role="button"]').first().click();
        await page.locator('#invoice-modal').waitFor({state:'visible'});
        assert.equal(await page.locator('#modal-inv-no').innerText(),'123');
        assert.equal(await page.locator('#modal-seller-mst').innerText(),'0123456789');
        assert.equal(await page.locator('#modal-buyer-mst').innerText(),'9876543210');
        assert.match(await page.locator('#modal-items-body').innerText(),/Sản phẩm mẫu/);
        assert.match(await page.locator('#modal-total-amount').innerText(),/1\.100/);
        assert.match(await page.locator('#modal-extra-info').innerText(),/invoice\.xml/);
        assert.equal(await page.locator('#modal-header-title').innerText(),'Chi tiết hóa đơn');
        assert.equal(await page.locator('#modal-sign-date, #modal-signature-badge, #btn-print-modal').count(),0);
        await page.locator('#btn-close-modal').click();
        await page.locator('#excel-table-body tr[role="button"]').first().focus();
        await page.keyboard.press('Enter');
        await page.locator('#invoice-modal').waitFor({state:'visible'});
        await page.locator('#btn-close-modal').click();
        await page.locator('[data-tab="tab-items"]').click();
        await page.waitForFunction(() => document.querySelector('#items-table-body').textContent.includes('Sản phẩm mẫu'));
        const headings = await page.locator('#tab-items th').allTextContents();
        assert.equal(headings.length,11);
        assert.ok(!headings.includes('Người bán') && !headings.includes('Mã hàng'));
        assert.match(await page.locator('#items-table-body').innerText(),/C26TAA/);
        assert.equal(await page.locator('#items-table-count').innerText(),'1 mặt hàng');
        await page.screenshot({path:path.join(root,'build/screens/invoice-products-v2.0.3.png')});
        await page.locator('[data-tab="tab-settings"]').click();
        assert.match(await page.locator('#tab-settings h3').first().innerText(), /Giao diện/);
        assert.equal(await page.locator('.theme-card').count(),8);
        assert.ok((await page.locator('#theme-cards-container').boundingBox()).height < 120);
        await page.locator('.theme-card[data-theme-id="ocean"]').count().then(async count => {if(count) await page.locator('.theme-card[data-theme-id="ocean"]').click();else await page.locator('.theme-card').nth(1).click();});
        assert.equal(await page.locator('.theme-card[aria-pressed="true"]').count(),1);
        await page.screenshot({path:path.join(root,'build/screens/compact-settings-v2.0.3.png')});
        await page.setViewportSize({width:1024,height:680});
        assert.ok((await page.locator('#theme-cards-container').boundingBox()).height < 120);
        assert.equal(hash(),before,'Xem hóa đơn không được sửa workbook');
        assert.deepEqual(writes,[]);
        assert.deepEqual(errors,[]);
        console.log('PASS: sidebar order, saved invoice modal, keyboard, saved products, compact themes, workbook bytes unchanged');
    } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
