const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
(async()=>{
    const root=path.resolve(__dirname,'..');
    const info=JSON.parse(fs.readFileSync(path.join(root,'build/scan-regression-info.json'),'utf8'));
    const fixtureRoot=path.dirname(path.resolve(info.folder));
    assert.ok(fixtureRoot.startsWith(path.join(root,'build')+path.sep));
    const browser=await chromium.launch({channel:'msedge',headless:true});
    try {
        const page=await browser.newPage({viewport:{width:1320,height:860}});
        const errors=[];page.on('pageerror',error=>errors.push(error.message));
        await page.route('**/api/check-update',route=>route.fulfill({json:{success:true,current_version:info.version,latest_version:info.version,has_update:false}}));
        const initial=await (await page.request.get(info.url+'/api/onboarding')).json();
        assert.equal(initial.required,true);
        assert.ok(path.resolve(initial.settings.excel_path).startsWith(fixtureRoot+path.sep));
        assert.equal(fs.existsSync(initial.settings.excel_path),false,'Không tạo workbook trước chọn nơi lưu');
        await page.goto(info.url);
        await page.locator('#startup-screen').waitFor({state:'detached'});
        await page.locator('#onboarding-modal').waitFor({state:'visible'});
        assert.equal(await page.locator('#btn-onboarding-complete').isDisabled(),true);
        assert.equal(await page.locator('#onboarding-accept').isChecked(),false);
        assert.equal(await page.locator('#app-content').evaluate(element=>element.inert),true);
        await page.locator('#onboarding-accept').focus();
        await page.keyboard.press('Tab');
        assert.equal(await page.locator('#onboarding-path').evaluate(element=>element===document.activeElement),true);
        await page.keyboard.press('Escape');
        assert.equal(await page.locator('#onboarding-modal').isVisible(),true);
        await page.locator('input[name="onboarding-theme"][value="teal"]').check();
        assert.equal(await page.locator('html').getAttribute('data-theme'),'teal');
        assert.equal((await (await page.request.get(info.url+'/api/onboarding')).json()).settings.theme,'rose','Xem trước chưa lưu cấu hình');
        const previewPath=await page.locator('#onboarding-path').inputValue();
        await page.locator('#onboarding-path').fill('C:\\HoaDon\\danh_sach_hoa_don.xlsx');
        await page.screenshot({path:path.join(root,'build/screens/first-run-v2.0.4.png')});
        await page.screenshot({path:path.join(root,'docs/first-run-preview.png')});
        await page.locator('#onboarding-path').fill(previewPath);
        await page.setViewportSize({width:1024,height:680});
        await page.screenshot({path:path.join(root,'build/screens/first-run-small-v2.0.4.png')});
        assert.ok((await page.locator('#onboarding-form').boundingBox()).height <= 680*0.92+1);
        await page.route('**/api/select-excel-save-dialog',route=>route.fulfill({json:{success:false,cancelled:true}}));
        const oldPath=await page.locator('#onboarding-path').inputValue();
        await page.locator('#btn-onboarding-browse').click();
        assert.equal(await page.locator('#onboarding-path').inputValue(),oldPath);
        await page.unroute('**/api/select-excel-save-dialog');
        await page.locator('#onboarding-accept').check();
        await page.locator('#onboarding-path').fill('invalid.xlsx');
        await page.locator('#btn-onboarding-complete').click();
        await page.locator('#onboarding-error').waitFor({state:'visible'});
        assert.equal(await page.locator('#onboarding-modal').isVisible(),true);
        const output=path.join(fixtureRoot,'chosen-output.xlsx');
        await page.route('**/api/select-excel-save-dialog',route=>route.fulfill({json:{success:true,filepath:output}}));
        await page.locator('#btn-onboarding-browse').click();
        await page.waitForFunction(expected=>document.getElementById('onboarding-path').value===expected,output);
        await page.locator('#btn-onboarding-complete').click();
        await page.locator('#onboarding-modal').waitFor({state:'hidden'});
        await page.waitForFunction(()=>document.activeElement.matches('.nav-tab[data-tab="tab-upload"]'));
        assert.equal(fs.existsSync(output),true);
        assert.equal(fs.existsSync(initial.settings.excel_path),false);
        let saved=await (await page.request.get(info.url+'/api/onboarding')).json();
        assert.equal(saved.required,false);assert.equal(saved.settings.theme,'teal');
        assert.equal(path.resolve(saved.settings.excel_path),path.resolve(output));
        assert.ok(saved.settings.accepted_terms_at);
        await page.reload();await page.locator('#startup-screen').waitFor({state:'detached'});
        assert.equal(await page.locator('#onboarding-modal').isHidden(),true);
        assert.equal(await page.locator('html').getAttribute('data-theme'),'teal');
        const persisted=page.waitForResponse(response=>response.url().endsWith('/api/settings')&&response.request().method()==='POST');
        await page.locator('#btn-toggle-sidebar').click();await persisted;
        await page.waitForFunction(()=>document.querySelector('#app-sidebar').getBoundingClientRect().width===76);
        assert.equal(await page.locator('#btn-toggle-sidebar').getAttribute('aria-expanded'),'false');
        await page.getByRole('button',{name:'Tổng quan',exact:true}).click();
        assert.equal(await page.locator('#tab-pivot').isVisible(),true);
        await page.reload();await page.locator('#startup-screen').waitFor({state:'detached'});
        await page.waitForFunction(()=>document.querySelector('#app-sidebar').getBoundingClientRect().width===76);
        assert.equal(await page.locator('#onboarding-modal').isHidden(),true);
        await page.getByRole('button',{name:'Cài Đặt',exact:true}).click();
        await page.locator('#btn-read-terms').click();
        await page.locator('#terms-modal').waitFor({state:'visible'});
        assert.match(await page.locator('#terms-modal').innerText(),/không thu hẹp/);
        await page.keyboard.press('Escape');
        assert.equal(await page.locator('#terms-modal').isHidden(),true);
        assert.equal(await page.locator('#app-content').evaluate(element=>element.inert),false);
        await page.locator('#btn-toggle-sidebar').click();
        await page.waitForFunction(()=>document.querySelector('#app-sidebar').getBoundingClientRect().width>76);
        assert.deepEqual(errors,[]);
        console.log('PASS: first-run path/theme/terms, cancel picker, invalid path, persistent acceptance, collapse/reload/navigation, terms reader');
    } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
